from contextlib import AbstractContextManager
from typing import Self

class MPFloat:
    def __add__(self, value: MPFloat) -> MPFloat: ...
    def __sub__(self, value: MPFloat) -> MPFloat: ...
    def __mul__(self, value: MPFloat) -> MPFloat: ...
    def __truediv__(self, value: MPFloat) -> MPFloat: ...
    def __eq__(self, value: MPFloat) -> bool: ...
    def __float__(self) -> float: ...

class MPContext:
    def mpf(self, value: str) -> MPFloat: ...
    def log(self, value: MPFloat) -> MPFloat: ...
    def workdps(
        self, digits: int, normalize_output: bool = False
    ) -> AbstractContextManager[Self]: ...

mp: MPContext
