from typing import Self

class mpf:
    def __init__(self, value: int | float | str | Self = ...) -> None: ...
    def __add__(self, other: int | float | str | Self) -> Self: ...
    def __radd__(self, other: int | float | str | Self) -> Self: ...
    def __sub__(self, other: int | float | str | Self) -> Self: ...
    def __rsub__(self, other: int | float | str | Self) -> Self: ...
    def __mul__(self, other: int | float | str | Self) -> Self: ...
    def __rmul__(self, other: int | float | str | Self) -> Self: ...
    def __truediv__(self, other: int | float | str | Self) -> Self: ...
    def __rtruediv__(self, other: int | float | str | Self) -> Self: ...
    def __pow__(self, other: int | float | Self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __lt__(self, other: int | float | Self) -> bool: ...
    def __le__(self, other: int | float | Self) -> bool: ...
    def __gt__(self, other: int | float | Self) -> bool: ...
    def __ge__(self, other: int | float | Self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __float__(self) -> float: ...

class _MPContext:
    dps: int

mp: _MPContext

def log(value: mpf) -> mpf: ...
def sqrt(value: mpf) -> mpf: ...
