sonar.organization=naslouby-salahe
sonar.projectKey=naslouby-salahe_TrajCert
sonar.projectName=TrajCert
sonar.sources=src/trajcert
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
