from typing import Self

class arb:
    def __init__(
        self,
        mid: int | float | str | Self | None = ...,
        rad: int | float | str | Self | None = ...,
    ) -> None: ...
    def __add__(self, other: int | float | Self) -> Self: ...
    def __radd__(self, other: int | float | Self) -> Self: ...
    def __sub__(self, other: int | float | Self) -> Self: ...
    def __rsub__(self, other: int | float | Self) -> Self: ...
    def __mul__(self, other: int | float | Self) -> Self: ...
    def __rmul__(self, other: int | float | Self) -> Self: ...
    def __truediv__(self, other: int | float | Self) -> Self: ...
    def __rtruediv__(self, other: int | float | Self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __lt__(self, other: int | float | Self) -> bool: ...
    def __le__(self, other: int | float | Self) -> bool: ...
    def __gt__(self, other: int | float | Self) -> bool: ...
    def __ge__(self, other: int | float | Self) -> bool: ...
    def log(self) -> Self: ...
    def lower(self) -> Self: ...
    def upper(self) -> Self: ...
    def man_exp(self) -> tuple[int, int]: ...
    def union(self, other: int | float | Self) -> Self: ...
    def min(self, other: int | float | Self) -> Self: ...
    def max(self, other: int | float | Self) -> Self: ...
    def is_zero(self) -> bool: ...
    def is_exact(self) -> bool: ...
    def is_finite(self) -> bool: ...

class _Context:
    prec: int

ctx: _Context
