class Arb:
    def __init__(self, value: str | float | int, radius: float = 0) -> None: ...
    def __add__(self, value: Arb) -> Arb: ...
    def __sub__(self, value: Arb) -> Arb: ...
    def __mul__(self, value: Arb) -> Arb: ...
    def __rmul__(self, value: Arb) -> Arb: ...
    def __truediv__(self, value: Arb) -> Arb: ...
    def __neg__(self) -> Arb: ...
    def log(self) -> Arb: ...
    def lower(self) -> Arb: ...
    def upper(self) -> Arb: ...
    def __float__(self) -> float: ...

class _Context:
    prec: int

arb: type[Arb]
ctx: _Context
