from io import BytesIO
from pathlib import Path

from matplotlib.axes import Axes
from matplotlib.text import Text

class Figure:
    def __init__(self, *, figsize: tuple[float, float] | None = ..., dpi: float | None = ...) -> None: ...
    def add_subplot(self, *args: int) -> Axes: ...
    def savefig(self, fname: str | Path | BytesIO, **kwargs: object) -> None: ...
    def subplots_adjust(self, **kwargs: float) -> None: ...
    def suptitle(self, t: str, **kwargs: object) -> Text: ...
