import numpy as np
from numpy.typing import NDArray

def entr[S: float | NDArray[np.float64]](x: S) -> S: ...
def expit[S: float | NDArray[np.float64]](x: S) -> S: ...
def betaln(a: float, b: float) -> float: ...
