from __future__ import annotations

from math import log
from pathlib import Path

from trajcert.types import BandCount

SEED_PREFIX = "TrajCert"
SEED_FIELD_SEPARATOR = "|"
SEED_MODULUS = 1 << 63
SEED_DIGEST_BYTES = 8
TERMINAL_CATEGORY_NAME = "infinity"
ENDPOINT_PARTITION_NAME = "Endpoint-only partition"
ENDPOINT_BAND_COUNT: BandCount = 1
BINARY_MAX_INFORMATION_NATS = log(2.0)
ENTROPY_MAXIMIZING_PROBABILITY = 0.5
RESOLVED_HARM_BOUNDARY_OFFSET = 0.005
INFORMATION_ROUNDOFF_ULPS = 32.0
ARB_INCUMBENT_BISECTION_ITERATIONS = 80
PRODUCTION_CONFIG_PATH = Path("configs/trajcert.yaml")
SMOKE_CONFIG_OVERRIDES_PATH = Path("configs/smoke.yaml")
TESTS_CONFIG_OVERRIDES_PATH = Path("configs/tests.yaml")

ARB_SEARCH_ROOT_SCAN_GRID_POINTS = 12
ARB_SEARCH_ROOT_SCAN_ENVELOPE_SPAN_FLOOR = 0.15
ARB_SEARCH_PROJECTION_STALL_MINIMUM_VISITED = 20000
ARB_SEARCH_PROJECTION_STALL_WINDOW_VISITED = 15000
ARB_SEARCH_PROJECTION_STALL_IMPROVEMENT_FLOOR = 1.0e-4
ARB_SEARCH_DECISION_STALL_MINIMUM_VISITED = 3000
ARB_SEARCH_DECISION_STALL_WINDOW_VISITED = 2000
ARB_SEARCH_DECISION_STALL_IMPROVEMENT_FLOOR = 1.0e-6
