from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from matplotlib.text import Text

class Axes:
    def add_patch(self, patch: Patch, **kwargs: object) -> Patch: ...
    def axhline(self, y: float = ..., **kwargs: object) -> Line2D: ...
    def axvline(self, x: float = ..., **kwargs: object) -> Line2D: ...
    def get_xlim(self) -> tuple[float, float]: ...
    def get_ylim(self) -> tuple[float, float]: ...
    def hlines(
        self, y: float, xmin: float, xmax: float, **kwargs: object
    ) -> LineCollection: ...
    def plot(self, *args: object, **kwargs: object) -> list[Line2D]: ...
    def set_title(self, label: str, **kwargs: object) -> Text: ...
    def set_xlim(self, left: float, right: float) -> tuple[float, float]: ...
    def set_ylim(self, bottom: float, top: float) -> tuple[float, float]: ...
    def set_visible(self, visible: bool) -> None: ...
    def step(self, *args: object, **kwargs: object) -> list[Line2D]: ...
    def text(self, x: float, y: float, text: str, **kwargs: object) -> Text: ...
